/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RedeRouteImport } from './routes/rede'
import { Route as JogadorIdRouteImport } from './routes/jogador.$id'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as PeladaIdRouteImport } from './routes/pelada.$id'
import { Route as PeladaIdAvaliarRouteImport } from './routes/pelada.$id.avaliar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeRoute = RedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadorIdRoute = JogadorIdRouteImport.update({
  id: '/jogador/$id',
  path: '/jogador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdRoute = PeladaIdRouteImport.update({
  id: '/pelada/$id',
  path: '/pelada/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdAvaliarRoute = PeladaIdAvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => PeladaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/criar': typeof CriarRoute
  '/perfil': typeof PerfilRoute
  '/rede': typeof RedeRoute
  '/jogador/$id': typeof JogadorIdRoute
  '/p/$token': typeof PTokenRoute
  '/pelada/$id': typeof PeladaIdRouteWithChildren
  '/pelada/$id/avaliar': typeof PeladaIdAvaliarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/criar': typeof CriarRoute
  '/perfil': typeof PerfilRoute
  '/rede': typeof RedeRoute
  '/jogador/$id': typeof JogadorIdRoute
  '/p/$token': typeof PTokenRoute
  '/pelada/$id': typeof PeladaIdRouteWithChildren
  '/pelada/$id/avaliar': typeof PeladaIdAvaliarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/criar': typeof CriarRoute
  '/perfil': typeof PerfilRoute
  '/rede': typeof RedeRoute
  '/jogador/$id': typeof JogadorIdRoute
  '/p/$token': typeof PTokenRoute
  '/pelada/$id': typeof PeladaIdRouteWithChildren
  '/pelada/$id/avaliar': typeof PeladaIdAvaliarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/criar'
    | '/perfil'
    | '/rede'
    | '/jogador/$id'
    | '/p/$token'
    | '/pelada/$id'
    | '/pelada/$id/avaliar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/criar'
    | '/perfil'
    | '/rede'
    | '/jogador/$id'
    | '/p/$token'
    | '/pelada/$id'
    | '/pelada/$id/avaliar'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buscar'
    | '/criar'
    | '/perfil'
    | '/rede'
    | '/jogador/$id'
    | '/p/$token'
    | '/pelada/$id'
    | '/pelada/$id/avaliar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CriarRoute: typeof CriarRoute
  PerfilRoute: typeof PerfilRoute
  RedeRoute: typeof RedeRoute
  JogadorIdRoute: typeof JogadorIdRoute
  PTokenRoute: typeof PTokenRoute
  PeladaIdRoute: typeof PeladaIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rede': {
      id: '/rede'
      path: '/rede'
      fullPath: '/rede'
      preLoaderRoute: typeof RedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogador/$id': {
      id: '/jogador/$id'
      path: '/jogador/$id'
      fullPath: '/jogador/$id'
      preLoaderRoute: typeof JogadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id': {
      id: '/pelada/$id'
      path: '/pelada/$id'
      fullPath: '/pelada/$id'
      preLoaderRoute: typeof PeladaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id/avaliar': {
      id: '/pelada/$id/avaliar'
      path: '/avaliar'
      fullPath: '/pelada/$id/avaliar'
      preLoaderRoute: typeof PeladaIdAvaliarRouteImport
      parentRoute: typeof PeladaIdRoute
    }
  }
}

interface PeladaIdRouteChildren {
  PeladaIdAvaliarRoute: typeof PeladaIdAvaliarRoute
}

const PeladaIdRouteChildren: PeladaIdRouteChildren = {
  PeladaIdAvaliarRoute: PeladaIdAvaliarRoute,
}

const PeladaIdRouteWithChildren = PeladaIdRoute._addFileChildren(
  PeladaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CriarRoute: CriarRoute,
  PerfilRoute: PerfilRoute,
  RedeRoute: RedeRoute,
  JogadorIdRoute: JogadorIdRoute,
  PTokenRoute: PTokenRoute,
  PeladaIdRoute: PeladaIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
