/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as PeladaIdRouteImport } from './routes/pelada.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PeladaIdRoute = PeladaIdRouteImport.update({
  id: '/pelada/$id',
  path: '/pelada/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/criar': typeof CriarRoute
  '/perfil': typeof PerfilRoute
  '/p/$token': typeof PTokenRoute
  '/pelada/$id': typeof PeladaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/criar': typeof CriarRoute
  '/perfil': typeof PerfilRoute
  '/p/$token': typeof PTokenRoute
  '/pelada/$id': typeof PeladaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/criar': typeof CriarRoute
  '/perfil': typeof PerfilRoute
  '/p/$token': typeof PTokenRoute
  '/pelada/$id': typeof PeladaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/criar' | '/perfil' | '/p/$token' | '/pelada/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/criar' | '/perfil' | '/p/$token' | '/pelada/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/criar'
    | '/perfil'
    | '/p/$token'
    | '/pelada/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CriarRoute: typeof CriarRoute
  PerfilRoute: typeof PerfilRoute
  PTokenRoute: typeof PTokenRoute
  PeladaIdRoute: typeof PeladaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelada/$id': {
      id: '/pelada/$id'
      path: '/pelada/$id'
      fullPath: '/pelada/$id'
      preLoaderRoute: typeof PeladaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CriarRoute: CriarRoute,
  PerfilRoute: PerfilRoute,
  PTokenRoute: PTokenRoute,
  PeladaIdRoute: PeladaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
